const difficulties = {
    "Effortless": "#7CFC90",
    "Easy": "#90EE90",
    "Medium": "#FFD700",
    "Hard": "#FFA500",
    "Difficult": "#FF4C4C",
    "Challenging": "#8B0000",
    "Intense": "#2F4F6F",
    "Remorseless": "#FF69B4",
    "Insane": "#0080FF",
    "Extreme": "#00BFFF",
    "Terrifying": "#00FFFF",
    "Catastrophic": "#FFFFFF",
    "Horrific": "#A53BF1",
    "Unreal": "#700196",
    "Nil": "#808080",
}

const difficultyWeight = {
    "Effortless": 0,
    "Easy": 1,
    "Medium": 2,
    "Hard": 3,
    "Difficult": 4,
    "Challenging": 5,
    "Intense": 6,
    "Remorseless": 7,
    "Insane": 8,
    "Extreme": 9,
    "Terrifying": 10,
    "Catastrophic": 11,
    "Horrific": 12,
    "Unreal": 13,
    "Nil": 14,
}